version: "3.9"

# ================================================
# ANCHORS
# ================================================

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "500k"
    max-file: "20"

# ================================================
# DEFINING SERVICES
# ================================================

services:
  dummy-port-scanner:
    container_name: dummy-port-scanner
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    logging: *default-logging
    networks: [ "dummy-port-scanner" ]

# ================================================
# DEFINING NETWORKS
# ================================================

networks:
  dummy-port-scanner:
