name: CI

on:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Secret Dection
        uses: zricethezav/gitleaks-action@master
        with:
          config-path: ${{ github.workspace }}/.gitleaks.toml
        continue-on-error: false

      - name: Hadolint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: ${{ github.workspace }}/Dockerfile
          config: ${{ github.workspace }}/.hadolint.yml
